export const FORENSIC_EVENT_TYPES = {
  FINAL_DOCUMENT_REGISTERED: 'FINAL_DOCUMENT_REGISTERED',
  FINAL_DOCUMENT_REMOVED: 'FINAL_DOCUMENT_REMOVED',
  SIGNATURE_RECORDED: 'SIGNATURE_RECORDED',
  DOCUMENT_CANCELED: 'DOCUMENT_CANCELED',
  VIDEO_ATTACHMENT_UPLOADED: 'VIDEO_ATTACHMENT_UPLOADED',
  VIDEO_ATTACHMENT_ACCESSED: 'VIDEO_ATTACHMENT_ACCESSED',
  VIDEO_ATTACHMENT_REMOVED: 'VIDEO_ATTACHMENT_REMOVED',
} as const;

export type ForensicEventType =
  (typeof FORENSIC_EVENT_TYPES)[keyof typeof FORENSIC_EVENT_TYPES];
