export const FORENSIC_EVENT_TYPES = {
  FINAL_DOCUMENT_REGISTERED: 'FINAL_DOCUMENT_REGISTERED',
  FINAL_DOCUMENT_REMOVED: 'FINAL_DOCUMENT_REMOVED',
  SIGNATURE_RECORDED: 'SIGNATURE_RECORDED',
  DOCUMENT_CANCELED: 'DOCUMENT_CANCELED',
} as const;

export type ForensicEventType =
  (typeof FORENSIC_EVENT_TYPES)[keyof typeof FORENSIC_EVENT_TYPES];
