export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  READ = 'READ',
  PRE_APPROVAL = 'PRE_APPROVAL',
  GDPR_ERASURE = 'GDPR_ERASURE',
  DATA_PORTABILITY = 'DATA_PORTABILITY',
}
