export const DISASTER_RECOVERY_DEFAULT_BACKUP_RETENTION_DAYS = 30;
export const DISASTER_RECOVERY_DEFAULT_RPO_HOURS = 24;
export const DISASTER_RECOVERY_DEFAULT_RTO_HOURS = 4;
export const DISASTER_RECOVERY_DEFAULT_BACKUP_ROOT = 'output/disaster-recovery';
export const DISASTER_RECOVERY_DEFAULT_STORAGE_BACKUP_PREFIX = 'dr-backups';
export const DISASTER_RECOVERY_PRODUCTION_CONFIRMATION_TOKEN =
  'RESTORE_PRODUCTION';
