import { ChecklistItemValue, ChecklistTopicValue } from './types/checklist-item.type';

export function buildNr24OperationalTopics(): ChecklistTopicValue[] {
  const createTopicItems = (items: string[]): ChecklistItemValue[] =>
    items.map((item) => ({
      item,
      tipo_resposta: 'sim_nao_na',
      obrigatorio: true,
    }));

  const topics: Array<{
    id: string;
    titulo: string;
    ordem: number;
    itens: string[];
  }> = [
    {
      id: 'nr24-topic-1',
      titulo: 'Aplicação e dimensionamento',
      ordem: 1,
      itens: [
        'O dimensionamento das instalações considera o número de trabalhadores usuários do turno de maior contingente?',
        'Os trabalhadores usuários das instalações estão corretamente identificados para o cálculo de dimensionamento?',
        'A quantidade de trabalhadores é compatível com a estrutura sanitária e de conforto disponível?',
        'Há separação por sexo das instalações quando exigida pela NR-24?',
        'Há condições operacionais para interrupção do trabalho e uso das instalações sem restrição indevida?',
      ],
    },
    {
      id: 'nr24-topic-2',
      titulo: 'Instalações sanitárias – exigência geral',
      ordem: 2,
      itens: [
        'Existe instalação sanitária disponível no estabelecimento ou frente de trabalho?',
        'Há bacia sanitária sifonada com assento e tampo nas instalações sanitárias?',
        'Há lavatório em número compatível com os trabalhadores usuários?',
        'Há mictório no sanitário masculino, aplica-se quando houver solução masculina e exigência dimensional?',
        'A quantidade mínima de instalações sanitárias atende ao efetivo do turno de maior contingente?',
        'Há privacidade de uso nas situações em que a norma admite uso comum?',
        'A quantidade total de sanitários é compatível com o efetivo usuário?',
      ],
    },
    {
      id: 'nr24-topic-3',
      titulo: 'Instalações sanitárias – condições construtivas e de conservação',
      ordem: 3,
      itens: [
        'As instalações sanitárias apresentam estado adequado de conservação?',
        'As instalações sanitárias estão limpas e higienizadas?',
        'O piso é impermeável e lavável?',
        'As paredes são impermeáveis e laváveis?',
        'A ventilação é adequada ao uso sanitário?',
        'Há ligação adequada com rede de água ou sistema equivalente?',
        'O esgotamento sanitário é adequado e sem extravasamentos?',
        'Existem recipientes para descarte de papéis usados?',
        'O acesso às instalações sanitárias é seguro e desobstruído?',
        'Quando os sanitários estão fora da edificação principal, há passagens cobertas e com piso adequado?',
      ],
    },
    {
      id: 'nr24-topic-4',
      titulo: 'Bacias sanitárias',
      ordem: 4,
      itens: [
        'As bacias sanitárias estão instaladas em compartimentos individualizados?',
        'Há privacidade efetiva de uso das bacias sanitárias?',
        'As portas dos compartimentos possuem fechamento adequado?',
        'Há fornecimento de papel higiênico em todos os compartimentos?',
        'Existe recipiente para descarte quando necessário?',
        'Há recipiente com tampa nos sanitários femininos?',
        'O espaço do compartimento é suficiente para uso adequado?',
        'As peças sanitárias estão conservadas e em funcionamento?',
      ],
    },
    {
      id: 'nr24-topic-5',
      titulo: 'Mictórios',
      ordem: 5,
      itens: [
        'Existe mictório quando aplicável ao sanitário masculino?',
        'O mictório adotado é individual ou coletivo em solução admitida pela norma?',
        'O dimensionamento dos mictórios atende ao efetivo usuário?',
        'O material dos mictórios é impermeável e apropriado à limpeza?',
        'Os mictórios estão conservados, limpos e higienizados?',
        'Há separação ou anteparo quando necessário para preservar privacidade?',
      ],
    },
    {
      id: 'nr24-topic-6',
      titulo: 'Lavatórios',
      ordem: 6,
      itens: [
        'Existem lavatórios em número suficiente para os trabalhadores usuários?',
        'O lavatório é individual ou coletivo conforme solução permitida?',
        'Há material ou dispositivo adequado para limpeza das mãos?',
        'Há meio adequado para enxugo ou secagem das mãos?',
        'Não há toalha coletiva para secagem das mãos?',
        'Os lavatórios e seu entorno estão conservados e higienizados?',
      ],
    },
    {
      id: 'nr24-topic-7',
      titulo: 'Chuveiros',
      ordem: 7,
      itens: [
        'A atividade desenvolvida exige a disponibilização de chuveiros?',
        'A quantidade de chuveiros atende ao número mínimo exigido, aplica-se quando houver obrigatoriedade?',
        'Os chuveiros estão localizados junto ao vestiário ou em área anexa adequada?',
        'Os chuveiros dispõem de compartimentos individualizados quando exigidos?',
        'Há privacidade adequada para uso dos chuveiros?',
        'As portas ou fechamentos dos chuveiros são adequados e funcionais?',
        'Há fornecimento de água fria e quente quando exigido?',
        'Há suporte para sabonete e toalha ou solução equivalente?',
        'O piso e as paredes da área de banho são impermeáveis e laváveis?',
        'As dimensões mínimas da área de banho são observadas quando aplicáveis?',
        'Os chuveiros estão limpos, conservados e em funcionamento?',
      ],
    },
    {
      id: 'nr24-topic-8',
      titulo: 'Vestiários – obrigatoriedade',
      ordem: 8,
      itens: [
        'Existe vestiário quando a troca de roupa precisa ocorrer no local de trabalho?',
        'Existe vestiário quando há uso de vestimenta de trabalho?',
        'Existe vestiário quando há necessidade de chuveiro?',
        'O vestiário é compatível com a atividade desenvolvida?',
      ],
    },
    {
      id: 'nr24-topic-9',
      titulo: 'Vestiários – dimensionamento e estrutura',
      ordem: 9,
      itens: [
        'A área do vestiário é compatível com o número de trabalhadores usuários?',
        'O dimensionamento geral do vestiário é adequado ao uso pretendido?',
        'O vestiário apresenta conservação, limpeza e higiene adequadas?',
        'A ventilação do vestiário é adequada?',
        'O piso do vestiário é impermeável e lavável?',
        'As paredes do vestiário são impermeáveis e laváveis quando exigido?',
        'Há assentos em número suficiente no vestiário?',
        'Os assentos são confeccionados em material lavável?',
        'A circulação interna é adequada e segura?',
        'A organização interna do vestiário é adequada ao uso?',
      ],
    },
    {
      id: 'nr24-topic-10',
      titulo: 'Armários',
      ordem: 10,
      itens: [
        'São fornecidos armários individuais aos trabalhadores quando exigidos?',
        'Os armários possuem sistema de trancamento?',
        'O tipo de armário simples ou duplo é compatível com o risco da atividade?',
        'Há separação entre roupa comum e roupa contaminada, aplica-se quando houver risco de contaminação?',
        'Os armários possuem dimensões mínimas adequadas ao uso?',
        'Os armários estão em bom estado de conservação?',
        'Os armários permitem a guarda de pertences pessoais?',
        'Os armários permitem a guarda das vestimentas de trabalho?',
        'O uso rotativo de armários ocorre somente quando permitido e com higienização prévia?',
      ],
    },
    {
      id: 'nr24-topic-11',
      titulo: 'Local para refeições – exigência geral',
      ordem: 11,
      itens: [
        'Existe local para refeição disponível aos trabalhadores?',
        'O local oferece conforto durante as refeições?',
        'O ambiente destinado às refeições apresenta condições adequadas de higiene?',
        'A estrutura do local para refeições é compatível com a quantidade de usuários?',
        'A organização dos turnos de refeição preserva o intervalo legal sem prejuízo ao acesso ao local?',
      ],
    },
    {
      id: 'nr24-topic-12',
      titulo: 'Local para refeições – estabelecimentos com até 30 trabalhadores',
      ordem: 12,
      itens: [
        'Há ambiente destinado ou adaptado para refeições em estabelecimentos com até 30 trabalhadores?',
        'O ambiente apresenta boas condições de ventilação?',
        'O ambiente apresenta boas condições de higiene?',
        'Há mesas, balcões ou similares para apoio da refeição?',
        'Há assentos suficientes para os usuários do local de refeições?',
        'Existem meios próximos para conservação dos alimentos?',
        'Existem meios próximos para aquecimento das refeições?',
        'Há local ou material adequado para lavagem de utensílios?',
        'Há fornecimento de água potável nas proximidades do local para refeições?',
      ],
    },
    {
      id: 'nr24-topic-13',
      titulo: 'Local para refeições – estabelecimentos com mais de 30 trabalhadores',
      ordem: 13,
      itens: [
        'Existe local exclusivo para refeições em estabelecimentos com mais de 30 trabalhadores?',
        'O local de refeições está situado fora da área de trabalho?',
        'O piso do local de refeições é lavável e impermeável?',
        'As paredes do local de refeições são laváveis e impermeáveis?',
        'Há espaço suficiente para circulação no local de refeições?',
        'A ventilação do local de refeições é adequada?',
        'Há lavatórios próximos ou no próprio local para refeições?',
        'Há assentos em número suficiente no local para refeições?',
        'As mesas possuem superfície lavável e em bom estado?',
        'Há água potável disponível no local de refeições?',
        'Existem meios para aquecimento de refeições no local?',
        'Existem recipientes com tampa para descarte de resíduos?',
        'O local para refeições está limpo e conservado?',
      ],
    },
    {
      id: 'nr24-topic-14',
      titulo: 'Dispensas e exceções relativas ao local de refeição',
      ordem: 14,
      itens: [
        'A hipótese de dispensa legal do local de refeições está corretamente enquadrada?',
        'O fornecimento de vale-refeição não está sendo usado para afastar obrigação de local quando ainda exigível?',
        'Existem condições para aquecer e conservar refeições trazidas de casa quando essa solução é admitida?',
        'Existe possibilidade real de o trabalhador realizar a refeição fora do estabelecimento nas hipóteses admitidas?',
      ],
    },
    {
      id: 'nr24-topic-15',
      titulo: 'Cozinhas',
      ordem: 15,
      itens: [
        'Existe cozinha quando há preparo de refeições no local?',
        'A cozinha está localizada de forma anexa ou funcionalmente integrada ao refeitório?',
        'O piso e as paredes da cozinha são impermeáveis e laváveis?',
        'A ventilação da cozinha é adequada?',
        'Há proteção contra insetos e vetores na cozinha?',
        'Existe lavatório exclusivo para manipuladores de alimentos?',
        'Há fornecimento de material para higienização das mãos?',
        'Não há toalha coletiva para secagem das mãos?',
        'O descarte de resíduos da cozinha é realizado de forma correta?',
        'Há sanitário exclusivo para manipuladores quando exigido?',
        'A câmara frigorífica possui dispositivo de segurança para abertura interna quando existente?',
        'O GLP é armazenado de forma adequada e segura?',
      ],
    },
    {
      id: 'nr24-topic-16',
      titulo: 'Alojamentos – existência e composição',
      ordem: 16,
      itens: [
        'Existe alojamento quando a empresa hospeda trabalhadores?',
        'A composição mínima do alojamento atende ao conjunto de ambientes exigidos pela norma?',
        'O alojamento possui dormitórios em quantidade e capacidade adequadas?',
        'O alojamento possui instalações sanitárias adequadas?',
        'O alojamento possui local para refeições ou acesso adequado à refeição?',
        'O alojamento dispõe de áreas de vivência adequadas?',
        'Existe local para lavagem e secagem de roupas?',
        'O empregador mantém as condições do alojamento em padrão adequado de uso e conservação?',
      ],
    },
    {
      id: 'nr24-topic-17',
      titulo: 'Dormitórios e quartos',
      ordem: 17,
      itens: [
        'Há separação por sexo nos dormitórios quando aplicável?',
        'O número de camas é compatível com o número de alojados?',
        'Não existem três ou mais camas na mesma vertical?',
        'Há armários para os trabalhadores alojados?',
        'A área mínima por cama é respeitada?',
        'O dormitório oferece conforto acústico adequado?',
        'As camas e beliches estão conservados e seguros?',
        'Não há arestas cortantes ou partes danificadas nas camas e beliches?',
        'Há escada fixa nos beliches?',
        'Há proteção lateral na cama superior dos beliches?',
        'A organização dos dormitórios considera turnos de trabalho quando recomendável?',
      ],
    },
    {
      id: 'nr24-topic-18',
      titulo: 'Alojamentos – higiene, conservação e apoio',
      ordem: 18,
      itens: [
        'Os sanitários do alojamento são limpos diariamente?',
        'Há coleta regular de lixo no alojamento?',
        'Há manutenção das instalações do alojamento em padrão adequado?',
        'As roupas de cama são lavadas e substituídas com frequência adequada?',
        'Colchões e enxoval estão em condições adequadas de higiene e conservação?',
        'Não há fogão ou fogareiro dentro dos quartos?',
        'Não há preparo de alimentos nos dormitórios?',
        'Existe lavanderia ou local adequado para lavagem e secagem de roupas pessoais?',
        'Há controle de vetores e pragas no alojamento?',
        'Existe procedimento para casos suspeitos de doença infectocontagiosa no alojamento?',
      ],
    },
    {
      id: 'nr24-topic-19',
      titulo: 'Vestimenta de trabalho',
      ordem: 19,
      itens: [
        'A vestimenta de trabalho é fornecida gratuitamente quando exigida?',
        'O material e o tamanho da vestimenta são adequados à atividade e ao trabalhador?',
        'Há quantidade suficiente de peças para trocas necessárias?',
        'A vestimenta é substituída quando danificada ou ao fim da vida útil?',
        'A higienização da vestimenta é de responsabilidade do empregador quando houver risco ocupacional?',
        'Há higienização prévia quando a vestimenta não é de uso exclusivo?',
        'Há distinção clara entre vestimenta de trabalho e EPI?',
        'Peças de cabeça ou face não restringem o campo de visão do trabalhador?',
      ],
    },
    {
      id: 'nr24-topic-20',
      titulo: 'Água potável',
      ordem: 20,
      itens: [
        'Há fornecimento de água potável a todos os trabalhadores?',
        'A quantidade de água potável é suficiente para o efetivo e a jornada?',
        'O número de bebedouros ou sistema equivalente atende ao mínimo necessário?',
        'Não há uso de copos coletivos para consumo de água?',
        'Os bebedouros estão limpos e em condições higiênicas adequadas?',
        'Quando não há água canalizada, o abastecimento ocorre por recipiente adequado?',
        'Os reservatórios de água são limpos e mantidos adequadamente?',
        'Há análise de potabilidade quando aplicável?',
        'A água não potável está identificada e segregada da água para consumo humano?',
        'Os pontos e recipientes de água potável estão protegidos contra contaminação?',
      ],
    },
    {
      id: 'nr24-topic-21',
      titulo: 'Limpeza, higiene e conservação geral',
      ordem: 21,
      itens: [
        'As condições gerais de higiene do ambiente de trabalho são adequadas?',
        'Existe rotina de limpeza definida e executada?',
        'A limpeza é realizada fora do horário de trabalho quando possível?',
        'São adotadas medidas para controle de poeira durante a limpeza?',
        'As instalações de conforto e vivência estão conservadas de forma geral?',
      ],
    },
    {
      id: 'nr24-topic-22',
      titulo: 'Requisitos construtivos gerais',
      ordem: 22,
      itens: [
        'As instalações atendem ao código de obras local e às exigências construtivas aplicáveis?',
        'As edificações possuem cobertura adequada à finalidade de uso?',
        'As paredes possuem resistência e integridade compatíveis com a utilização?',
        'Os pisos são adequados ao uso e à circulação prevista?',
        'A iluminação é suficiente e segura para uso das instalações?',
        'O pé-direito mínimo é observado quando aplicável?',
        'As instalações elétricas estão protegidas e em condições seguras?',
        'Existem medidas de proteção contra choque elétrico nas áreas de vivência e conforto?',
        'A construção é compatível com a finalidade de uso das instalações de conforto e vivência?',
        'As condições de circulação são seguras em todos os acessos e ambientes?',
      ],
    },
    {
      id: 'nr24-topic-23',
      titulo: 'Anexo I – Shopping Center',
      ordem: 23,
      itens: [
        'A administração central fornece sanitários, vestiários e local para refeições quando aplicável aos trabalhadores dos lojistas?',
        'Os trabalhadores dos lojistas sem estrutura própria adequada são efetivamente atendidos pela administração central?',
        'Há local para conservação e aquecimento de refeições quando exigido pelo anexo?',
        'Há vestiário para troca de roupa e guarda de pertences quando exigido?',
        'Há chuveiros quando exigidos pelo tipo de atividade atendida?',
        'O dimensionamento das estruturas compartilhadas considera o número de trabalhadores atendidos?',
      ],
    },
    {
      id: 'nr24-topic-24',
      titulo: 'Anexo II – trabalho externo de prestação de serviços',
      ordem: 24,
      itens: [
        'Há instalações sanitárias disponíveis nas frentes de trabalho e atividades externas?',
        'Há bacia sanitária e lavatório em quantidade adequada aos trabalhadores presentes?',
        'Quando adotado, o banheiro químico está em conformidade com as exigências aplicáveis?',
        'O banheiro químico recebe higienização diária?',
        'Existe local protegido para refeições nas atividades externas?',
        'O custeio da alimentação é observado quando a norma admitir essa solução?',
        'Há fornecimento de água fresca e potável aos trabalhadores externos?',
        'Há meios para conservação e aquecimento dos alimentos próprios dos trabalhadores?',
        'O uso das instalações sanitárias pelos trabalhadores é gratuito?',
        'Há transporte para local conveniado quando essa solução é utilizada?',
      ],
    },
    {
      id: 'nr24-topic-25',
      titulo: 'Anexo III – transporte público rodoviário coletivo urbano em atividade externa',
      ordem: 25,
      itens: [
        'Existem instalações próximas ao ponto inicial ou final da linha quando não houver terminal?',
        'A distância máxima de deslocamento a pé até a instalação atende ao limite normativo aplicável?',
        'Há instalações sanitárias em quantidade adequada ao contingente simultâneo?',
        'As instalações sanitárias oferecem privacidade e higiene adequadas?',
        'Quando utilizado, o banheiro químico atende às condições aplicáveis do anexo?',
        'Há local para refeições protegido contra intempéries?',
        'Há água potável suficiente para a jornada dos trabalhadores externos?',
        'Existe reposição adequada da água potável durante a jornada?',
        'O dimensionamento considera o número máximo de trabalhadores presentes simultaneamente?',
        'O uso das instalações sanitárias é gratuito para os trabalhadores?',
        'Quando permitido, o atendimento por convênio ou parceria garante acesso efetivo e adequado aos trabalhadores?',
      ],
    },
  ];

  return topics.map((topic) => ({
    id: topic.id,
    titulo: topic.titulo,
    ordem: topic.ordem,
    itens: createTopicItems(topic.itens),
  }));
}
