import { ChecklistItemValue, ChecklistTopicValue } from './types/checklist-item.type';

export function buildPemtTopics(): ChecklistTopicValue[] {
  type PemtItemDefinition = {
    subitem: string;
    item: string;
    criticidade?: 'critico' | 'alto' | 'medio' | 'baixo';
    bloqueia?: boolean;
    observacaoObrigatoria?: boolean;
    fotoObrigatoria?: boolean;
    acao?: string;
  };

  const createTopicItems = (
    items: PemtItemDefinition[],
  ): ChecklistItemValue[] =>
    items.map((definition) => ({
      item: `${definition.subitem} - ${definition.item}`,
      tipo_resposta: 'sim_nao_na',
      obrigatorio: true,
      criticidade: definition.criticidade,
      bloqueia_operacao_quando_nc: definition.bloqueia,
      exige_observacao_quando_nc:
        definition.observacaoObrigatoria ?? Boolean(definition.bloqueia),
      exige_foto_quando_nc: definition.fotoObrigatoria,
      acao_corretiva_imediata: definition.acao,
    }));

  const topics: Array<{
    id: string;
    titulo: string;
    ordem: number;
    itens: PemtItemDefinition[];
  }> = [
    {
      id: 'pemt-topic-1',
      titulo: 'Documentação e Liberação',
      ordem: 1,
      itens: [
        {
          subitem: 'Manual',
          item: 'Manual do fabricante disponível para consulta',
          criticidade: 'alto',
          acao: 'Disponibilizar o manual atualizado no local ou em meio digital antes da liberação.',
        },
        {
          subitem: 'Identificação',
          item: 'Equipamento identificado por código, número de patrimônio, série ou frota',
          criticidade: 'alto',
          acao: 'Regularizar a identificação física e sistêmica do equipamento antes do uso.',
        },
        {
          subitem: 'Capacidade',
          item: 'Capacidade máxima de carga identificada e legível',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Bloquear o equipamento até restabelecer a identificação legível da capacidade nominal.',
        },
        {
          subitem: 'Advertências',
          item: 'Sinalizações de segurança e advertência legíveis',
          criticidade: 'alto',
          fotoObrigatoria: true,
          acao: 'Substituir ou recompor as sinalizações obrigatórias antes da liberação.',
        },
        {
          subitem: 'Inspeção periódica',
          item: 'Registro de inspeção periódica atualizado',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Executar a inspeção periódica pendente e manter o equipamento bloqueado até aprovação.',
        },
        {
          subitem: 'Manutenção',
          item: 'Registro de manutenção preventiva e corretiva atualizado',
          criticidade: 'alto',
          acao: 'Atualizar a rastreabilidade de manutenção e revisar a condição de liberação.',
        },
        {
          subitem: 'Liberação',
          item: 'Equipamento formalmente liberado para uso',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Impedir o uso até regularização formal da condição de liberação.',
        },
        {
          subitem: 'Procedimento',
          item: 'Procedimento operacional disponível para a atividade',
          criticidade: 'alto',
          acao: 'Disponibilizar o procedimento aplicável e orientar a equipe antes do início.',
        },
        {
          subitem: 'Análise de risco',
          item: 'Análise de risco elaborada para a atividade',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Suspender a atividade e elaborar a análise de risco antes da operação.',
        },
        {
          subitem: 'Permissão de trabalho',
          item: 'Permissão de trabalho emitida quando exigível',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Bloquear a operação até emissão e validação formal da PT exigida.',
        },
      ],
    },
    {
      id: 'pemt-topic-2',
      titulo: 'Estrutura Geral do Equipamento',
      ordem: 2,
      itens: [
        {
          subitem: 'Chassi',
          item: 'Chassi sem trincas, amassamentos ou deformações',
          criticidade: 'critico',
          bloqueia: true,
          fotoObrigatoria: true,
          acao: 'Retirar o equipamento de operação e encaminhar para avaliação estrutural imediata.',
        },
        {
          subitem: 'Plataforma',
          item: 'Cesto ou plataforma em bom estado estrutural',
          criticidade: 'critico',
          bloqueia: true,
          fotoObrigatoria: true,
          acao: 'Bloquear o equipamento até correção estrutural e reinspeção.',
        },
        {
          subitem: 'Guarda-corpo',
          item: 'Guarda-corpo íntegro e firmemente fixado',
          criticidade: 'critico',
          bloqueia: true,
          fotoObrigatoria: true,
          acao: 'Impedir o uso até recomposição integral do sistema de proteção coletiva.',
        },
        {
          subitem: 'Portão de acesso',
          item: 'Portão ou barra de acesso em perfeito estado e fechamento adequado',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Bloquear o equipamento até restabelecer o fechamento seguro do acesso.',
        },
        {
          subitem: 'Corrosão',
          item: 'Ausência de corrosão severa em partes estruturais',
          criticidade: 'critico',
          bloqueia: true,
          fotoObrigatoria: true,
          acao: 'Interditar o equipamento para avaliação estrutural e reparo.',
        },
        {
          subitem: 'Vazamentos',
          item: 'Ausência de vazamentos aparentes',
          criticidade: 'alto',
          fotoObrigatoria: true,
          acao: 'Paralisar a operação, identificar a origem do vazamento e reparar antes da liberação.',
        },
        {
          subitem: 'Limpeza',
          item: 'Equipamento limpo e sem acúmulo excessivo de sujeira',
          criticidade: 'medio',
          acao: 'Executar limpeza segura e reinspecionar o equipamento antes do uso.',
        },
      ],
    },
    {
      id: 'pemt-topic-3',
      titulo: 'Sistema Elétrico e Energização',
      ordem: 3,
      itens: [
        {
          subitem: 'Cabos',
          item: 'Cabos, chicotes e conexões sem danos',
          criticidade: 'critico',
          bloqueia: true,
          fotoObrigatoria: true,
          acao: 'Bloquear o equipamento e substituir os componentes elétricos danificados.',
        },
        {
          subitem: 'Fios expostos',
          item: 'Ausência de fios expostos',
          criticidade: 'critico',
          bloqueia: true,
          fotoObrigatoria: true,
          acao: 'Interditar imediatamente o equipamento até correção elétrica.',
        },
        {
          subitem: 'Painéis',
          item: 'Painéis elétricos fechados e protegidos',
          criticidade: 'alto',
          acao: 'Restabelecer fechamento e proteção do compartimento antes do uso.',
        },
        {
          subitem: 'Bateria',
          item: 'Bateria em boas condições de uso',
          criticidade: 'critico',
          bloqueia: true,
          fotoObrigatoria: true,
          acao: 'Retirar de operação e corrigir o sistema de alimentação antes do uso.',
        },
        {
          subitem: 'Carga',
          item: 'Nível de carga adequado para operação',
          criticidade: 'alto',
          acao: 'Encaminhar o equipamento para recarga antes da liberação.',
        },
        {
          subitem: 'Carregador',
          item: 'Sistema de recarga em condição segura',
          criticidade: 'alto',
          acao: 'Proibir a recarga até regularizar o sistema e substituir componentes avariados.',
        },
        {
          subitem: 'Comandos elétricos',
          item: 'Comandos elétricos respondem normalmente',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Bloquear o equipamento e encaminhar para diagnóstico elétrico ou eletrônico.',
        },
      ],
    },
    {
      id: 'pemt-topic-4',
      titulo: 'Comandos e Testes Funcionais',
      ordem: 4,
      itens: [
        {
          subitem: 'Comando de base',
          item: 'Comandos da base funcionando corretamente',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Retirar de operação até reparo e reteste funcional.',
        },
        {
          subitem: 'Comando da plataforma',
          item: 'Comandos da plataforma funcionando corretamente',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Bloquear imediatamente o equipamento até correção.',
        },
        {
          subitem: 'Emergência',
          item: 'Botão de parada de emergência funcionando',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Interditar o equipamento imediatamente.',
        },
        {
          subitem: 'Descida de emergência',
          item: 'Sistema de descida de emergência funcionando',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Bloquear a liberação do equipamento até reparo e teste validado.',
        },
        {
          subitem: 'Alarme',
          item: 'Alarme sonoro operacional',
          criticidade: 'alto',
          acao: 'Corrigir o dispositivo antes de liberar o uso em área operacional.',
        },
        {
          subitem: 'Indicadores',
          item: 'Painel e indicadores funcionando corretamente',
          criticidade: 'alto',
          acao: 'Corrigir o sistema de indicação antes do uso.',
        },
        {
          subitem: 'Elevação',
          item: 'Movimento de elevação sem falhas ou ruídos anormais',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Paralisar o equipamento e encaminhar para inspeção técnica.',
        },
        {
          subitem: 'Descida',
          item: 'Movimento de descida sem falhas ou ruídos anormais',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Bloquear o equipamento até reparo e reteste.',
        },
        {
          subitem: 'Translação',
          item: 'Movimento de deslocamento funcionando corretamente',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Impedir uso da função e bloquear o equipamento se a falha comprometer a segurança.',
        },
        {
          subitem: 'Sensores',
          item: 'Sensores e limitadores de segurança operantes',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Interditar o equipamento imediatamente.',
        },
      ],
    },
    {
      id: 'pemt-topic-5',
      titulo: 'Rodas, Pneus e Estabilidade',
      ordem: 5,
      itens: [
        {
          subitem: 'Pneus',
          item: 'Pneus ou rodas em boas condições',
          criticidade: 'alto',
          fotoObrigatoria: true,
          acao: 'Retirar de operação até substituição ou reparo.',
        },
        {
          subitem: 'Fixação',
          item: 'Rodas e componentes de fixação firmes',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Bloquear imediatamente até reaperto técnico ou substituição.',
        },
        {
          subitem: 'Eixos',
          item: 'Eixos sem danos aparentes',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Interditar o equipamento até avaliação e reparo.',
        },
        {
          subitem: 'Estabilizadores',
          item: 'Estabilizadores em perfeito estado e funcionamento',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Bloquear o uso até restabelecer a estabilidade prevista pelo fabricante.',
        },
        {
          subitem: 'Nivelamento',
          item: 'Sistema de nivelamento funcionando',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Impedir a operação até correção do sistema.',
        },
        {
          subitem: 'Apoio',
          item: 'Equipamento apoiado corretamente no piso',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Reposicionar o equipamento e reavaliar a condição do piso antes da operação.',
        },
      ],
    },
    {
      id: 'pemt-topic-6',
      titulo: 'Dispositivos de Segurança',
      ordem: 6,
      itens: [
        {
          subitem: 'Guarda-corpo',
          item: 'Guarda-corpo completo e sem improvisos',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Bloquear a liberação até recomposição integral do guarda-corpo.',
        },
        {
          subitem: 'Acesso',
          item: 'Sistema de fechamento do acesso funcionando',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Impedir operação até correção do mecanismo de acesso.',
        },
        {
          subitem: 'Ancoragem',
          item: 'Ponto de ancoragem identificado e íntegro',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Bloquear o uso até restabelecer ponto homologado pelo fabricante.',
        },
        {
          subitem: 'Proteção contra quedas',
          item: 'Sistema de proteção contra quedas conforme fabricante',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Suspender a atividade e adequar o sistema de retenção conforme especificação técnica.',
        },
        {
          subitem: 'Alça de apoio',
          item: 'Alça de apoio interno íntegra',
          criticidade: 'alto',
          acao: 'Substituir o componente antes da operação.',
        },
        {
          subitem: 'Sensor de inclinação',
          item: 'Sensor de inclinação operante',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Interditar o equipamento até reparo.',
        },
        {
          subitem: 'Horímetro',
          item: 'Horímetro funcionando',
          criticidade: 'medio',
          acao: 'Corrigir o instrumento e ajustar o controle de manutenção.',
        },
        {
          subitem: 'Bloqueio',
          item: 'Sistema de bloqueio contra uso indevido funcionando',
          criticidade: 'alto',
          acao: 'Restabelecer o controle de acesso antes da liberação.',
        },
      ],
    },
    {
      id: 'pemt-topic-7',
      titulo: 'EPI e Proteção contra Quedas',
      ordem: 7,
      itens: [
        {
          subitem: 'Cinturão',
          item: 'Cinturão de segurança em boas condições',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Substituir imediatamente o EPI e impedir o início da atividade até regularização.',
        },
        {
          subitem: 'Talabarte',
          item: 'Talabarte ou sistema indicado em boas condições',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Retirar o EPI de uso e substituir antes da operação.',
        },
        {
          subitem: 'Conectores',
          item: 'Mosquetões e conectores em bom estado',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Substituir imediatamente o componente defeituoso.',
        },
        {
          subitem: 'Conexão correta',
          item: 'Sistema conectado ao ponto correto de ancoragem',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Interromper a atividade imediatamente e reconectar conforme orientação do fabricante.',
        },
        {
          subitem: 'Inspeção prévia',
          item: 'EPI inspecionado antes do uso',
          criticidade: 'alto',
          acao: 'Realizar inspeção imediata e substituir qualquer item inadequado.',
        },
        {
          subitem: 'Orientação',
          item: 'Trabalhadores orientados sobre uso correto do EPI',
          criticidade: 'alto',
          acao: 'Realizar orientação imediata antes do início da atividade.',
        },
      ],
    },
    {
      id: 'pemt-topic-8',
      titulo: 'Operador e Equipe',
      ordem: 8,
      itens: [
        {
          subitem: 'Capacitação',
          item: 'Operador capacitado para operar a plataforma',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Impedir a operação por esse trabalhador até regularização formal.',
        },
        {
          subitem: 'Autorização',
          item: 'Operador formalmente autorizado',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Suspender o uso e regularizar a autorização formal.',
        },
        {
          subitem: 'Aptidão',
          item: 'Trabalhador apto para a atividade',
          criticidade: 'alto',
          acao: 'Impedir a participação até validação ocupacional, quando aplicável.',
        },
        {
          subitem: 'Orientação da equipe',
          item: 'Equipe orientada sobre riscos e controles da atividade',
          criticidade: 'alto',
          acao: 'Realizar briefing operacional antes do início da tarefa.',
        },
        {
          subitem: 'Emergência',
          item: 'Equipe ciente dos procedimentos de emergência',
          criticidade: 'alto',
          acao: 'Suspender a atividade até alinhamento do plano de resposta.',
        },
        {
          subitem: 'Limites do equipamento',
          item: 'Operador conhece capacidade e limitações da plataforma',
          criticidade: 'alto',
          acao: 'Reforçar a orientação e impedir operação até evidência de entendimento.',
        },
        {
          subitem: 'Uso indevido',
          item: 'Não há uso por pessoa não autorizada',
          criticidade: 'alto',
          acao: 'Restabelecer o bloqueio de acesso e reforçar o controle operacional.',
        },
      ],
    },
    {
      id: 'pemt-topic-9',
      titulo: 'Condições do Local',
      ordem: 9,
      itens: [
        {
          subitem: 'Piso',
          item: 'Piso firme e resistente para suportar o equipamento',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Proibir o posicionamento até definição de base segura ou tratamento do piso.',
        },
        {
          subitem: 'Nivelamento',
          item: 'Piso nivelado ou dentro do limite aceitável do fabricante',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Reposicionar o equipamento ou suspender a atividade.',
        },
        {
          subitem: 'Desníveis',
          item: 'Ausência de buracos, valas e desníveis críticos',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Isolar a área e redefinir trajeto ou posição segura.',
        },
        {
          subitem: 'Obstáculos',
          item: 'Área de circulação desobstruída',
          criticidade: 'alto',
          acao: 'Desobstruir a área antes da movimentação.',
        },
        {
          subitem: 'Afundamento',
          item: 'Ausência de risco de afundamento',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Bloquear a operação e estabilizar ou adequar a base de apoio.',
        },
        {
          subitem: 'Isolamento',
          item: 'Área isolada e sinalizada',
          criticidade: 'alto',
          acao: 'Isolar e sinalizar adequadamente antes de iniciar a atividade.',
        },
        {
          subitem: 'Iluminação',
          item: 'Iluminação adequada para operação segura',
          criticidade: 'alto',
          acao: 'Complementar a iluminação ou suspender a atividade.',
        },
        {
          subitem: 'Clima',
          item: 'Condições climáticas seguras para operação',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Suspender imediatamente a atividade e recolher a plataforma.',
        },
      ],
    },
    {
      id: 'pemt-topic-10',
      titulo: 'Riscos Elétricos e Interferências',
      ordem: 10,
      itens: [
        {
          subitem: 'Rede elétrica',
          item: 'Distância segura de redes elétricas energizadas',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Bloquear a atividade imediatamente e redefinir o método com controle elétrico formal.',
        },
        {
          subitem: 'Obstáculos superiores',
          item: 'Ausência de risco de choque com estruturas aéreas',
          criticidade: 'alto',
          acao: 'Redefinir o posicionamento e limitar a movimentação até eliminar o risco.',
        },
        {
          subitem: 'Interferência lateral',
          item: 'Ausência de interferência lateral perigosa',
          criticidade: 'alto',
          acao: 'Reposicionar o equipamento ou isolar a interferência.',
        },
        {
          subitem: 'Sinalização',
          item: 'Sinalização de risco elétrico instalada quando necessária',
          criticidade: 'alto',
          acao: 'Instalar a sinalização e as barreiras antes da liberação.',
        },
        {
          subitem: 'Suspensão da atividade',
          item: 'Atividade suspensa em condição insegura',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Determinar paralisação imediata, isolar o equipamento e revisar a atividade.',
        },
      ],
    },
    {
      id: 'pemt-topic-11',
      titulo: 'Regras de Operação Segura',
      ordem: 11,
      itens: [
        {
          subitem: 'Capacidade',
          item: 'Capacidade máxima da plataforma respeitada',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Retirar o excesso de carga e reavaliar a condição antes do uso.',
        },
        {
          subitem: 'Carga útil',
          item: 'Transporte apenas de pessoas, ferramentas e materiais necessários',
          criticidade: 'alto',
          acao: 'Retirar materiais indevidos antes da operação.',
        },
        {
          subitem: 'Improviso',
          item: 'Ausência de improvisos para ganho de altura',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Interromper imediatamente a atividade e retirar o improviso.',
        },
        {
          subitem: 'Uso inadequado',
          item: 'Equipamento não utilizado como guindaste',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Suspender a atividade e adequar o método de movimentação.',
        },
        {
          subitem: 'Deslocamento',
          item: 'Deslocamento realizado com velocidade compatível',
          criticidade: 'alto',
          acao: 'Interromper o deslocamento e reforçar a regra operacional com o operador.',
        },
        {
          subitem: 'Visibilidade',
          item: 'Operação realizada com visibilidade adequada',
          criticidade: 'alto',
          acao: 'Suspender a atividade ou adicionar apoio operacional e controle adicional.',
        },
        {
          subitem: 'Limites do fabricante',
          item: 'Operação dentro dos limites definidos pelo fabricante',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Paralisar a operação e replanejar a atividade conforme limite técnico aplicável.',
        },
        {
          subitem: 'Anormalidade',
          item: 'Paralisação imediata em caso de falha ou anormalidade',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Bloquear imediatamente o equipamento e abrir ocorrência formal.',
        },
      ],
    },
    {
      id: 'pemt-topic-12',
      titulo: 'Inspeção Pré-Uso Diária',
      ordem: 12,
      itens: [
        {
          subitem: 'Rotina',
          item: 'Inspeção realizada antes do início do turno',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Suspender a atividade até execução da inspeção formal.',
        },
        {
          subitem: 'Checklist',
          item: 'Checklist diário preenchido',
          criticidade: 'alto',
          acao: 'Exigir o preenchimento do checklist antes da liberação do turno.',
        },
        {
          subitem: 'Teste funcional',
          item: 'Teste funcional executado antes da liberação',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Bloquear o uso até execução dos testes mínimos obrigatórios.',
        },
        {
          subitem: 'Comunicação',
          item: 'Falhas comunicadas imediatamente ao responsável',
          criticidade: 'alto',
          acao: 'Registrar e comunicar imediatamente ao responsável pela liberação.',
        },
        {
          subitem: 'Bloqueio',
          item: 'Equipamento bloqueado em caso de defeito',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Aplicar bloqueio imediato e retirar o equipamento da área operacional.',
        },
        {
          subitem: 'Registro da NC',
          item: 'Não conformidade registrada formalmente',
          criticidade: 'alto',
          acao: 'Abrir registro formal da não conformidade imediatamente.',
        },
      ],
    },
    {
      id: 'pemt-topic-13',
      titulo: 'Manutenção e Controle',
      ordem: 13,
      itens: [
        {
          subitem: 'Preventiva',
          item: 'Plano de manutenção preventiva implementado',
          criticidade: 'alto',
          acao: 'Implantar ou regularizar o plano preventivo e reavaliar a liberação.',
        },
        {
          subitem: 'Corretiva',
          item: 'Manutenção corretiva registrada adequadamente',
          criticidade: 'medio',
          acao: 'Regularizar a documentação da intervenção realizada.',
        },
        {
          subitem: 'Qualificação',
          item: 'Manutenção executada por profissional qualificado',
          criticidade: 'alto',
          acao: 'Reavaliar a intervenção e submeter o equipamento à revisão técnica qualificada.',
        },
        {
          subitem: 'Peças',
          item: 'Peças e componentes adequados utilizados na manutenção',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Substituir por componente adequado e reinspecionar o equipamento.',
        },
        {
          subitem: 'Teste pós-manutenção',
          item: 'Equipamento testado após manutenção',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Suspender a liberação e executar reteste formal.',
        },
        {
          subitem: 'Interdição',
          item: 'Equipamento interditado claramente identificado quando inapto',
          criticidade: 'critico',
          bloqueia: true,
          acao: 'Aplicar identificação e bloqueio físico imediatamente.',
        },
      ],
    },
    {
      id: 'pemt-topic-14',
      titulo: 'Finalização e Pós-Uso',
      ordem: 14,
      itens: [
        {
          subitem: 'Recolhimento',
          item: 'Plataforma recolhida ao final da atividade',
          criticidade: 'alto',
          acao: 'Recolher imediatamente a estrutura e revisar a orientação da equipe.',
        },
        {
          subitem: 'Desligamento',
          item: 'Equipamento desligado de forma segura',
          criticidade: 'alto',
          acao: 'Realizar desligamento seguro e reforçar a rotina de encerramento.',
        },
        {
          subitem: 'Estacionamento',
          item: 'Equipamento estacionado em local adequado',
          criticidade: 'alto',
          acao: 'Reposicionar imediatamente em local definido e seguro.',
        },
        {
          subitem: 'Bloqueio contra uso indevido',
          item: 'Acesso ao equipamento bloqueado após uso',
          criticidade: 'alto',
          acao: 'Aplicar controle de acesso e recolher os meios de acionamento.',
        },
        {
          subitem: 'Recarga',
          item: 'Bateria encaminhada para recarga quando necessário',
          criticidade: 'medio',
          acao: 'Encaminhar o equipamento para recarga segura conforme procedimento.',
        },
        {
          subitem: 'Registro',
          item: 'Falhas observadas após uso registradas e comunicadas',
          criticidade: 'alto',
          acao: 'Registrar imediatamente a anomalia e bloquear o equipamento se houver risco.',
        },
      ],
    },
  ];

  return topics.map((topic) => ({
    id: topic.id,
    titulo: topic.titulo,
    ordem: topic.ordem,
    itens: createTopicItems(topic.itens),
  }));
}
